# Generated by Django 2.2.4 on 2020-02-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productid',
        ),
    ]
