# Generated by Django 2.2.4 on 2020-02-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200217_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageid',
        ),
    ]
